# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-25 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('about', models.TextField(null=True)),
                ('interest', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.Case')),
                ('humans', models.ManyToManyField(to='human.Human')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.Skill'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.Human'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.Skill'),
        ),
    ]
