# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 12:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_auto_20190303_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='希望工作地點'),
        ),
    ]
