# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0004_auto_20190519_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhuman',
            name='moneyRequired',
            field=models.PositiveIntegerField(default=100, verbose_name='要求時薪'),
            preserve_default=False,
        ),
    ]
