# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0005_itemhuman_moneyrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhuman',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='同意'),
        ),
        migrations.AddField(
            model_name='itemhuman',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='選定'),
        ),
    ]
