# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0006_auto_20190519_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhuman',
            name='hours',
            field=models.PositiveIntegerField(null=True, verbose_name='時數'),
        ),
        migrations.AlterField(
            model_name='itemhuman',
            name='money',
            field=models.PositiveIntegerField(null=True, verbose_name='時薪'),
        ),
    ]
